spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/naaam-h-siddhu/RapidShine-Configurations
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
server:
  port: 8888